server:
  port: 8081
spring:
  cloud:
    stream:
      bindings:
        input: testtock
#      module:
#        redis:
#          sink:
#            port: 6379
#            host: 127.0.0.1
#            sentinel:
#              master: mymaster
#              nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
#            queue: myQueue
