server:
  port: 8080
fixedDelay: 5000
spring:
  cloud:
    stream:
      bindings:
        output: testtock

---
spring:
  profiles: extended
  cloud:
    stream:
      bindings:
        output: xformed
